apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}      
  name: {{ .Release.Name }}
  labels:
    run: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
  ports:
  - port: {{ .Values.listenport }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}

